server:
  port: 8090
spring:
  application:
      name: orderplace
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/productdb
    username: root
    password: 
  jpa:
    generate-ddl: true
    show-sql: true
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
  instance:
    preferIpAddress: true    